### ISSUE TITLE
Resolving local hostnames?

### ISSUE THREAD

**Issue by boldarevbogdan** [tableau/react-native-dns-lookup#7]
Hi. First of all i want to thank you for this package. You did a great job. 
My question is, can i use this package to get local ip using mdns hostname (ended with .local)? 
If so, can you provide an example?

**Comment by avertin** [comment]
Hi @boldarevbogdan, thanks for the question. I haven't tested getting a local ip before. I'll have some time in the next few weeks to investigate and get back to you. If you happen to try in the meantime, let me know what you discover.

**Comment by absurdprofit** [comment]
Any follow up on this? I really need this. By the way avertin really did a good job with this. I need mDNS lookup for local hostname on android. I've tried every other option it seems none worked even though the device I'm trying to discover and resolve hostname appears in bonjour browser.

**Comment by absurdprofit** [comment]
When I type hostname ending in .local it says unable to resolve host. But when I try the IP address itself, it returns a list containing that same IP address I fed it, i.e. getIpAddressesForHostname("192.168.100.70") returns ["192.168.100.70"].

**Comment by avertin** [comment]
@nxtexe @boldarevbogdan I still haven't had a chance to investigate but it's on my radar. It may ultimately be a limitation of the underlying native libraries that this module leverages, but I'll look into it.

**Comment by absurdprofit** [comment]
Ok np, for me I got zeroconf to work. But I still think your solution is much simpler and straight to the point. If I could switch I happily would.

**Comment by avertin** [comment]
@nxtexe @boldarevbogdan could you give me an example of how to set up a local ip? I'm not sure how to test this functionality that you are asking for.

**Comment by absurdprofit** [comment]
I was setting up a service for my raspberry pi. [This](https://www.raspberrypi.org/forums/viewtopic.php?t=267113) is the tutorial I followed.

**Comment by absurdprofit** [comment]
You could also used react-native-zeroconf to publish a service from a mobile device then try to resolve the mobile device IP from it's published service name.

**Comment by avertin** [comment]
Thanks for your patience while I investigated this. After looking into it more, I've decided that support for .local domains w/MDNS is out of scope for this library. The reason my solution is "simpler and straight to the point" is because it doesn't need to support MDNS. When I looked into what it would take to implement this (especially for Android), the solution was exactly what [react-native-zeroconf](https://github.com/balthazar/react-native-zeroconf) is already doing. For future developers running into this issue, I'd recommend using that library as @nxtexe suggested.
